### ISSUE TITLE
Bookmarks are scrolled horizontally

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-frontend#10]
Problem: while I have a lot of space on the screen, it is not utilized and the horizontal scroll is added.

![2017-01-23-201136_1918x1060_scrot](https://cloud.githubusercontent.com/assets/1366419/22216609/74d7eef2-e1a8-11e6-8c63-c759ae2189fb.png)

Possible solutions:
- (preferred) Re-design page to show a list of bookmarks.
- Insert breaks when there are too many bookmarks.

**Comment by drets** [comment]
@rasendubi is it fixed? :stuck_out_tongue_winking_eye:

**Comment by rasendubi** [comment]
oh, yeah. thanks you!
