### ISSUE TITLE
Not mobile-friendly

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-frontend#20]
![screenshot_20170129-191045](https://cloud.githubusercontent.com/assets/1366419/22406194/2141c764-e657-11e6-992f-8d47318fbf60.png)

**Comment by rasendubi** [comment]
As a first step, I would move the buttons and hide them under menu.

**Comment by drets** [comment]
On my Nexus 5 it looks even worse.

At least login screen **is** mobile-friendly! :wink:

**Comment by drets** [comment]
@rasendubi what the status of this issue?

**Comment by rasendubi** [comment]
thanks, fixed by #24.
