### ISSUE TITLE
Scroll does not work with Vimium

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-frontend#28]
Problem: I use Vimium and none of the scrolling commands work (scroll by lines `h/j`, scroll by pages `u/d`, go to beginning/end `gg/G`)

**Comment by rasendubi** [comment]
Well, this does seem to be fixed somehow. I'll reopen if I see this again.

**Comment by drets** [comment]
Well, I suppose it was on Vimium side (it should properly inject a script to the page).
