### ISSUE TITLE
Unable to edit saved article title

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-frontend#29]
Problem: I have added showing page URL in the title (for better self-tracking), so now I have bookmarks with titles like `How to brain-dump what you know – [http://sachachua.com][blog/2010/03/how-to-brain-dump-what-you-know/]`. I would like to remove the link part, but the only way I can do that now is by opening the link, deleting it, and saving again (changing the title). That's inconvenient and messes up save timestamp.

Solution: Implement editing article on the frontend.

**Comment by drets** [comment]
> I have added showing page URL in the title (for better self-tracking)

Could you share how? Do you use another extension for that?

> Solution: Implement editing article on the frontend.

We could try to transform a title during saving in extension. Why do you prefer this feature on frontend first?
(of course in the long run we should have every piece of information editable from everywhere)

**Comment by rasendubi** [comment]
I use [Url in title](https://chrome.google.com/webstore/detail/url-in-title/ignpacbgnbnkaiooknalneoeladjnfgb) extension.

I prefer editing on the frontend because I don't pay much attention to the title while saving (I just save-save-save most of my tabs). When I open on the frontend later, I'm in a less rush, so I prefer editing the title at that time.

Ok, now I came up with two more solutions:
Solution 2: programmatically transform titles on the extension side. This either allows user write arbitrary javascript, or use regular expressions.

Solution 3: download page from the backend side and parse original title. This looks ok, as we're going to implement [saving content](https://github.com/heutagogy/heutagogy-backend/issues/3) on backend anyway.

**Comment by drets** [comment]
@rasendubi fixed?

**Comment by rasendubi** [comment]
Yes. Fixed by #46.
