### ISSUE TITLE
Cannot export all bookmarks in one go

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-frontend#33]
Problem: I cannot export all my bookmarks in one go. If I select all bookmarks, only the current page is exported. (Though, if you browse through the pages, all bookmarks are selected.)

**Comment by drets** [comment]
Thank you for turning my caveats in PR descriptions into the issues :+1: 

As for _solution_ I'd move the exporting feature to the separate modal window (similar to the importing modal window).

**Comment by rasendubi** [comment]
Fixed by #54.
